swagger: "2.0"
info:
  description: "Sample Banking API"
  version: 1.0.0
  title: MyBankingAPI YAML
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: /v1
tags:
  - name: customer
    description: The customer
    externalDocs:
      description: Find out more
      url: ""
schemes:
  - http
paths:
  /customers:
    get:
      tags:
        - customer
      summary: Get a list of customers
      description: ""
      operationId: getCustomers
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/xml
        - application/json
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Customer"
        "405":
          description: Validation exception
  "/customers/{id}":
    get:
      tags:
        - customer
      summary: Get a customer by id
      x-swagger-router-controller: MyBankingApiController
      description: Returns a single customer
      operationId: getCustomer
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of customer to return
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Customer"
        "400":
          description: Invalid ID supplied
        "404":
          description: Customer not found
definitions:
  Customer:
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Bob
      type:
        $ref: "#/definitions/CustomerType"
    xml:
      name: Customer
  CustomerType:
    properties:
      type:
        type: string
        description: customer type
        enum:
          - gold
          - silver
          - bronze
    xml:
      name: CustomerType
externalDocs:
  description: Find out more about MyBank
  url: "http://mybank.com"
